backbone: vgg16
batch_size: 32
dataset: outex10
encoder_type: fv
exp_dir: experiments_fvcnn/outex10-vgg16-20260119-231916
feature_layer: conv5_3
fold: 0
framework: fvcnn
gmm_components: 64
l2_normalize: true
max_sqrt_hw: 1024
min_edge: 30
num_classes: 24
pca_dim: null
resize: 128
root_dir: data/datasets/Outex-TC-00010
scales:
- 1.4142
- 1.0
- 0.7071
- 0.5
- 0.3536
- 0.25
- 0.1768
- 0.125
- 0.0884
- 0.0625
seed: 42
signed_sqrt: true
svm_C: 1.0
svm_calibration: false
test_ratio: 0.15
train_ratio: 0.5
train_val_ratio: 2
vmap_chunk_size: 50
