
base_config: configs/curet.yaml
sweep:
  resize: 200 #128
  classifier_epochs: [40]
  conv_epochs: [30]
  max_scale: [4]
  nb_orients: [6]
  out_size: [4] #, 2]
  n_copies: [1] #, 12]
  #lr: [0.01, 0.001, 0.0001]
  lr: [0.025]
  lambda_reg: [1e-3, 1e-4, 1e-2]
  weight_decays: [1e-3]
  #radius: [0.05, 0.1, 1.0]
  seed: [123] #, 456, 789]
  share_channels: false
  pca_dim: [22]
  train_ratio:
    # start: 0.2949 
    # stop: 0.1
    # step: -0.06
    start: 0.54 #0.46 #0.5899
    stop: 0.1 #0.2
    step: -0.06
  

