
base_config: configs/curet.yaml
sweep:
  classifier_epochs: [10, 15]
  conv_epochs: [10, 15]
  train_ratio:
    start: 0.01
    stop: 0.31
    step: 0.02
  lr: [0.05]
  lambda_reg: [1e-3, 1e-4, 1e-5]
  nb_orients: [4, 6, 8]
  

