base_config: configs/curet.yaml
sweep:
  classifier_epochs: [10, 15]
  conv_epochs: [10, 15]
  train_size: [null, 500, 1000]  # Optional: Sweep over fixed training dataset sizes
  val_ratio: 0.1  # Fixed validation ratio
  lr: [0.01, 0.001, 0.0001]
  lambda_reg: [1e-3, 1e-4, 1e-5]
  nb_orients: [4, 6, 8]


