
base_config: configs/curet.yaml
sweep:
  classifier_epochs: [2]
  conv_epochs: [2]
  train_ratio:
    start: 0.1
    stop: 0.825
    step: 0.02
  #lr: [0.01, 0.001, 0.0001]
  lambda_reg: [1, 1e-1, 1e-2, 1e-3]
  nb_orients: [6]
  share_channels: [true, false]
  

