
base_config: configs/curet.yaml
sweep:
  classifier_epochs: [40]
  conv_epochs: [30]
  max_scale: [3, 5]
  nb_orients: [4, 8]
  out_size: [4, 8]
  #lr: [0.01, 0.001, 0.0001]
  lr: [0.005]
  weight_decays: [1e-3]
  #radius: [0.05, 0.1, 1.0]
  seed: [123, 456, 789]
  share_channels: [true, false]
  train_ratio:
    start: 0.2
    stop: 0.46
    step: 0.06
  

