
base_config: configs/curet.yaml
sweep:
  resize: 200 #128
  classifier_epochs: [40]
  conv_epochs: [30]
  max_scale: [4, 5]
  nb_orients: [6]
  out_size: [-1] #, 2]
  n_copies: [12] #, 12]
  #lr: [0.01, 0.001, 0.0001]
  lr: [0.025]
  lambda_reg: [1e-4, 1e-3, 1e-2]
  weight_decays: [1e-3]
  #radius: [0.05, 0.1, 1.0]
  seed: [123] #, 456, 789]
  share_channels: false
  pca_dim: [22, 6]
  train_ratio:
    start: 0.589 #0.46
    stop: 0.2
    step: -0.06
  

