
base_config: configs/curet.yaml
sweep:
  classifier_epochs: [15]
  conv_epochs: [20]
  train_ratio:
    start: 0.01
    stop: 0.31
    step: 0.02
  lr: [0.05, 0.01, 0.001]
  weight_decays: [1e-3, 1e-4, 1e-5]
  nb_orients: [4, 6, 8]
  radius: [0.1, 1.0, 5.0]
  seed: [123, 456, 789, 101112, 131415]
  share_channels: [true, false]
  

