# This is a sweep config file for hyperparameter tuning on MNIST dataset
# It uses the base configuration from mnist.yaml and overrides specific parameters for the sweep
base_config: configs/mnist.yaml
sweep:
  classifier_epochs: [10]
  conv_epochs: [10]
  train_ratio:
    start: 0.01
    stop: 0.31
    step: 0.02
  # lr: [0.01, 0.001, 0.0001]
  lambda_reg: [1e-1, 1e-2, 1e-3, 1e-5]
  # nb_orients: [4, 6, 8]


