# This is a sweep config file for hyperparameter tuning on MNIST dataset
# It uses the base configuration from mnist.yaml and overrides specific parameters for the sweep
base_config: configs/mnist.yaml
sweep:
  classifier_epochs: [10, 15]
  conv_epochs: [10, 15]
  val_ratio: [0.1, 0.2, 0.4]
  lr: [0.01, 0.001, 0.0001]
  lambda_reg: [1e-3, 1e-4, 1e-5]
  nb_orients: [4, 6, 8]
  train_size: [null, 500, 5000, 10000]  # Optional: Sweep over fixed training dataset sizes


