# This is a sweep config file for hyperparameter tuning on MNIST dataset
# It uses the base configuration from mnist.yaml and overrides specific parameters for the sweep
base_config: configs/mnist.yaml
sweep:
  classifier_epochs: [15]
  conv_epochs: [15]
  train_ratio:
    start: 0.005
    stop: 0.02
    step: 0.0005
  lr: [0.01, 0.001]
  lambda_reg: [1e-3, 1e-4]
  nb_orients: [4, 6]
  wavelet: [meyer]
  batch_size: [64]


