# model setting
wavelet: meyer
max_scale: 2
nb_orients: 4
efficient: true
isShared: true
# training setting
dataset: mnist
classifier_epochs: 10
conv_epochs: 10
batch_size: 200
lr: 0.05
lambda_reg: 1e-1
train_ratio: 0.85
val_ratio: 0.1

