backbone: vgg16
batch_size: 16
dataset: mnist
exp_dir: experiments_fvcnn/mnist-vgg16-20260119-232148
exp_root: experiments_fvcnn
feature_layer: conv5_3
framework: fvcnn
gmm_components: 32
gmm_samples: 10000
l2_normalize: true
max_sqrt_hw: 512
min_edge: 5
pca_dim: null
resize: 28
root_dir: data/MNIST
scales:
- 1.0
- 0.5
seed: 42
signed_sqrt: true
svm_C: 1.0
